#######################################################################################
# Book settings
title: "atomate2"
author: Alex Ganose
email: a.ganose@imperial.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Atomate2 documentation.

exclude_patterns: [file-types/include-rst.rst]

# Bibliography settings
bibtex_bibfiles:
  - references.bib

execute:
  execute_notebooks: cache

html:
  #announcement: "⚠️The latest release refactored our HTML, so double-check your custom CSS rules!⚠️"
  favicon: images/favicon.ico
  #google_analytics_id: UA-52617120-7
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://materialsproject.github.io/atomate2/

repository:
  url: https://github.com/materialsproject/atomate2
  branch: main
  path_to_book: docs

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

parse:
  myst_substitutions:
      sub3: My _global_ value!
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    # TODO: #917 this path will be the default in sphinx v4
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # However, it is incompatible with the mathjax config below for macros
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    latex_elements:
        preamble: |
          \newcommand\N{\mathbb{N}}
          \newcommand\floor[1]{\lfloor#1\rfloor}
          \newcommand{\bmat}{\left[\begin{array}}
          \newcommand{\emat}{\end{array}\right]}
    intersphinx_mapping:
      python:
        - "https://docs.python.org/3.8"
        - null
      matplotlib:
        - "http://matplotlib.org"
        - null
      pymatgen:
        - "http://pymatgen.org"
        - null
      jobflow:
        - "https://materialsproject.github.io/jobflow"
        - null
      monty:
        - "https://guide.materialsvirtuallab.org/monty"
        - null
    language: en
    html_extra_path:
      - images/badge.svg
    html_static_path:
      - _static
    html_css_files:
      - custom.css
    templates_path:
      - "_templates"
      - components

    # autodoc options
    autosummary_imported_members: false
    autodoc_preserve_defaults: true
    autoclass_content: class
    autodoc_member_order: bysource
    python_use_unqualified_type_names: true

    # don't overwrite summary but generate them if they don't exist
    autosummary_generate: true
    autosummary_generate_overwrite: true

    # numpydoc options
    numpydoc_class_members_toctree: false
    numpydoc_show_class_members: false
    numpydoc_show_inherited_class_members: false
    numpydoc_attributes_as_param_list: false
    numpydoc_xref_param_type: true

    # sphinx-panels shouldn't add bootstrap css as the pydata-sphinx-theme already loads it
    panels_add_bootstrap_css: false

    # control pydantic model docs
    autodoc_pydantic_model_show_json: false
    autodoc_pydantic_model_show_field_summary: false
    autodoc_pydantic_model_show_config: false
    autodoc_pydantic_model_show_config_summary: false
    autodoc_pydantic_model_show_validator_members: false
    autodoc_pydantic_model_member_order: bysource
    autodoc_pydantic_settings_show_json: false
    autodoc_pydantic_settings_show_field_summary: false
    autodoc_pydantic_settings_show_config: false
    autodoc_pydantic_settings_show_config_summary: false
    autodoc_pydantic_settings_show_validator_members: false
    autodoc_pydantic_settings_member_order: bysource
    autodoc_pydantic_field_list_validators: false
    autodoc_pydantic_field_show_constraints: false


  extra_extensions:
    - sphinx.ext.autodoc
    - numpydoc
    - sphinx.ext.intersphinx
    - sphinx.ext.viewcode
    - sphinx.ext.autosummary
    - sphinx_panels
    - sphinxcontrib.autodoc_pydantic
