# Number of electrons for each element in each pseudopotential
GBRV:
  suffixes:
    - _pbe.uspp
  Cd: 12
  Be: 4
  Br: 7
  Fe: 16
  K: 9
  Rb: 9
  Os: 16
  La: 11
  Tc: 15
  Ni: 18
  Te: 6
  Ti: 12
  Rh: 15
  Ga: 19
  Se: 6
  Au: 11
  Mn: 15
  Ru: 16
  Zr: 12
  Pd: 16
  Re: 15
  F: 7
  N: 5
  Cs: 9
  Sn: 14
  Hg: 12
  Ta: 13
  Ir: 15
  Hf: 12
  Ca: 10
  Si: 4
  Sr: 10
  Bi: 15
  Li: 3
  W: 14
  B: 3
  P: 5
  As: 5
  Ge: 14
  V: 13
  Zn: 20
  Mg: 10
  Y: 11
  Pb: 14
  Sb: 15
  Al: 3
  Ba: 10
  Cr: 14
  Mo: 14
  I: 7
  O: 6
  Nb: 13
  Ag: 19
  Cu: 19
  Tl: 13
  C: 4
  Co: 17
  Pt: 16
  S: 6
  Na: 9
  Sc: 11
  Cl: 7
  In: 13
  H: 1

GBRV_v1.5:
  Cd: 12
  Be: 4
  Br: 7
  Fe: 16
  K: 9
  Rb: 9
  Os: 16
  La: 11
  Tc: 15
  Ni: 18
  Te: 6
  Ti: 12
  Rh: 15
  Ga: 19
  Se: 6
  Au: 11
  Mn: 15
  Ru: 16
  Zr: 12
  Pd: 16
  Re: 15
  F: 7
  N: 5
  Cs: 9
  Sn: 14
  Hg: 12
  Ta: 13
  Ir: 15
  Hf: 12
  Ca: 10
  Si: 4
  Sr: 10
  Bi: 15
  Li: 3
  W: 14
  B: 3
  P: 5
  As: 5
  Ge: 14
  V: 13
  Zn: 20
  Mg: 10
  Y: 11
  Pb: 14
  Sb: 15
  Al: 3
  Ba: 10
  Cr: 14
  Mo: 14
  I: 7
  O: 6
  Nb: 13
  Ag: 19
  Cu: 19
  Tl: 13
  C: 4
  Co: 17
  Pt: 16
  S: 6
  Na: 9
  Sc: 11
  Cl: 7
  In: 13
  H: 1

SG15:
  Cd: 12
  Be: 4
  Br: 7
  Fe: 16
  K: 9
  Rb: 9
  Os: 16
  La: 11
  Tc: 15
  Ni: 18
  Te: 6
  Ti: 12
  Rh: 15
  Ga: 19
  Se: 6
  Au: 11
  Mn: 15
  Ru: 16
  Zr: 12
  Pd: 16
  Re: 15
  F: 7
  N: 5
  Cs: 9
  Sn: 14
  Hg: 12
  Ta: 13
  Ir: 15
  Hf: 12
  Ca: 10
  Si: 4
  Sr: 10
  Bi: 15
  Li: 3
  W: 14
  B: 3
  P: 5
  As: 5
  Ge: 14
  V: 13
  Zn: 20
  Mg: 10
  Y: 11
  Pb: 14
  Sb: 15
  Al: 3
  Ba: 10
  Cr: 14
  Mo: 14
  I: 7
  O: 6
  Nb: 13
  Ag: 19
  Cu: 19
  Tl: 13
  C: 4
  Co: 17
  Pt: 16
  S: 6
  Na: 9
  Sc: 11
  Cl: 7
  In: 13
  H: 1