name: Merge dependencies

on:
  workflow_run:
    workflows:
      - Run tests
    types:
      - completed

jobs:
  merge-deps:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dependabot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAXIMUM_RETRIES: 2
